/* Generated by tools/verify-scaffold.mjs. Do not edit. */
import * as M_alert from '@suite/components/ui/alert';
import * as M_apple_spotlight from '@suite/components/block/apple-spotlight';
import * as M_arrow_fill_button from '@suite/components/block/arrow-fill-button';
import * as M_art_gallery from '@suite/components/block/art-gallery';
import * as M_avatar from '@suite/components/ui/avatar';
import * as M_badge from '@suite/components/ui/badge';
import * as M_book_flip from '@suite/components/block/book-flip';
import * as M_breadcrumb from '@suite/components/ui/breadcrumb';
import * as M_butterfly_trail_cursor from '@suite/components/block/butterfly-trail-cursor';
import * as M_button from '@suite/components/ui/button';
import * as M_button_group from '@suite/components/ui/button-group';
import * as M_calendar from '@suite/components/ui/button';
import * as M_card from '@suite/components/ui/card';
import * as M_carousel from '@suite/components/ui/button';
import * as M_chart from '@suite/components/ui/chart';
import * as M_checkbox from '@suite/components/ui/checkbox';
import * as M_circle_menu from '@suite/components/block/circle-menu';
import * as M_click_spark from '@suite/components/block/click-spark';
import * as M_collapsible from '@suite/components/ui/collapsible';
import * as M_colorful_cursor_aura from '@suite/components/block/colorful-cursor-aura';
import * as M_command from '@suite/components/ui/command';
import * as M_context_menu from '@suite/components/ui/context-menu';
import * as M_curved_plane from '@suite/components/block/curved-plane';
import * as M_dialog from '@suite/components/ui/dialog';
import * as M_dither_canvas from '@suite/components/block/dither-canvas';
import * as M_dotted_grid from '@suite/components/block/dotted-grid';
import * as M_draggable_marquee from '@suite/components/block/draggable-marquee';
import * as M_drawer from '@suite/components/ui/drawer';
import * as M_dropdown_menu from '@suite/components/ui/dropdown-menu';
import * as M_empty from '@suite/components/ui/empty';
import * as M_field from '@suite/components/ui/field';
import * as M_file_input from '@suite/components/block/file-input';
import * as M_flip_scroll from '@suite/components/block/flip-scroll';
import * as M_flip_text from '@suite/components/block/flip-text';
import * as M_flow_scroll from '@suite/components/block/flow-scroll';
import * as M_folder_preview from '@suite/components/block/folder-preview';
import * as M_footer from '@suite/components/block/footer';
import * as M_form from '@suite/components/ui/form';
import * as M_fractal_glass from '@suite/components/block/fractal-glass';
import * as M_glowing_scroll_indicator from '@suite/components/block/glowing-scroll-indicator';
import * as M_grid_lift from '@suite/components/block/grid-lift';
import * as M_horizontal_scroll from '@suite/components/block/horizontal-scroll';
import * as M_hover_card from '@suite/components/ui/hover-card';
import * as M_hover_img from '@suite/components/block/hover-img';
import * as M_input from '@suite/components/ui/input';
import * as M_input_group from '@suite/components/ui/button';
import * as M_input_otp from '@suite/components/ui/input-otp';
import * as M_interactive_arrows from '@suite/components/block/interactive-arrows';
import * as M_interactive_blur_reveal from '@suite/components/block/interactive-blur-reveal';
import * as M_interactive_hover_button from '@suite/components/block/interactive-hover-button';
import * as M_interactive_hover_slider from '@suite/components/block/interactive-hover-slider';
import * as M_item from '@suite/components/ui/item';
import * as M_jelly_loader from '@suite/components/block/jelly-loader';
import * as M_kbd from '@suite/components/ui/kbd';
import * as M_label from '@suite/components/ui/label';
import * as M_liquid_metal from '@suite/components/block/liquid-metal';
import * as M_magnet_tabs from '@suite/components/block/magnet-tabs';
import * as M_magnetic_image_trail from '@suite/components/block/magnetic-image-trail';
import * as M_mask_cursor_effect from '@suite/components/block/mask-cursor-effect';
import * as M_masonry_grid from '@suite/components/block/masonry-grid';
import * as M_menubar from '@suite/components/ui/menubar';
import * as M_navigation_menu from '@suite/components/ui/navigation-menu';
import * as M_otp_input from '@suite/components/block/otp-input';
import * as M_pagination from '@suite/components/ui/button';
import * as M_parallax_gallery from '@suite/components/block/parallax-gallery';
import * as M_pixelated_carousel from '@suite/components/block/pixelated-carousel';
import * as M_playground_button from '@suite/components/block/playground-button';
import * as M_playground_navbar from '@suite/components/block/playground-navbar';
import * as M_popover from '@suite/components/ui/popover';
import * as M_progress from '@suite/components/ui/progress';
import * as M_radio_group from '@suite/components/ui/radio-group';
import * as M_raised_button from '@suite/components/ui/raised-button';
import * as M_rectangular_text_reveal from '@suite/components/block/rectangular-text-reveal';
import * as M_resizable from '@suite/components/ui/resizable';
import * as M_ripple_pulse_loader from '@suite/components/ui/ripple-pulse-loader';
import * as M_rope_cursor from '@suite/components/block/rope-cursor';
import * as M_scroll_area from '@suite/components/ui/scroll-area';
import * as M_scroll_effect from '@suite/components/block/scroll-effect';
import * as M_scroll_stack from '@suite/components/block/scroll-stack';
import * as M_select from '@suite/components/ui/select';
import * as M_separator from '@suite/components/ui/separator';
import * as M_sheet from '@suite/components/ui/sheet';
import * as M_sidebar from '@suite/components/ui/button';
import * as M_sidebar_stackbits from '@suite/components/block/sidebar-stackbits';
import * as M_skeleton from '@suite/components/ui/skeleton';
import * as M_skeumorphic_music_card from '@suite/components/block/skeumorphic-music-card';
import * as M_slider from '@suite/components/ui/slider';
import * as M_smooth_scroll from '@suite/components/block/smooth-scroll';
import * as M_sonner from '@suite/components/ui/sonner';
import * as M_spinner from '@suite/components/ui/spinner';
import * as M_svg_path_marquee from '@suite/components/block/svg-path-marquee';
import * as M_svg_pixel_reveal from '@suite/components/block/svg-pixel-reveal';
import * as M_switch from '@suite/components/ui/switch';
import * as M_table from '@suite/components/ui/table';
import * as M_tabs from '@suite/components/ui/tabs';
import * as M_text_fill_animation from '@suite/components/block/text-fill-animation';
import * as M_text_stream from '@suite/components/block/text-stream';
import * as M_textarea from '@suite/components/ui/textarea';
import * as M_toggle from '@suite/components/ui/toggle';
import * as M_toggle_group from '@suite/components/ui/toggle-group';
import * as M_tooltip from '@suite/components/ui/tooltip';
import * as M_trading_card from '@suite/components/block/trading-card';
import * as M_visitor_count from '@suite/components/block/visitor-count';

const modules = {
  'alert': M_alert,
  'apple-spotlight': M_apple_spotlight,
  'arrow-fill-button': M_arrow_fill_button,
  'art-gallery': M_art_gallery,
  'avatar': M_avatar,
  'badge': M_badge,
  'book-flip': M_book_flip,
  'breadcrumb': M_breadcrumb,
  'butterfly-trail-cursor': M_butterfly_trail_cursor,
  'button': M_button,
  'button-group': M_button_group,
  'calendar': M_calendar,
  'card': M_card,
  'carousel': M_carousel,
  'chart': M_chart,
  'checkbox': M_checkbox,
  'circle-menu': M_circle_menu,
  'click-spark': M_click_spark,
  'collapsible': M_collapsible,
  'colorful-cursor-aura': M_colorful_cursor_aura,
  'command': M_command,
  'context-menu': M_context_menu,
  'curved-plane': M_curved_plane,
  'dialog': M_dialog,
  'dither-canvas': M_dither_canvas,
  'dotted-grid': M_dotted_grid,
  'draggable-marquee': M_draggable_marquee,
  'drawer': M_drawer,
  'dropdown-menu': M_dropdown_menu,
  'empty': M_empty,
  'field': M_field,
  'file-input': M_file_input,
  'flip-scroll': M_flip_scroll,
  'flip-text': M_flip_text,
  'flow-scroll': M_flow_scroll,
  'folder-preview': M_folder_preview,
  'footer': M_footer,
  'form': M_form,
  'fractal-glass': M_fractal_glass,
  'glowing-scroll-indicator': M_glowing_scroll_indicator,
  'grid-lift': M_grid_lift,
  'horizontal-scroll': M_horizontal_scroll,
  'hover-card': M_hover_card,
  'hover-img': M_hover_img,
  'input': M_input,
  'input-group': M_input_group,
  'input-otp': M_input_otp,
  'interactive-arrows': M_interactive_arrows,
  'interactive-blur-reveal': M_interactive_blur_reveal,
  'interactive-hover-button': M_interactive_hover_button,
  'interactive-hover-slider': M_interactive_hover_slider,
  'item': M_item,
  'jelly-loader': M_jelly_loader,
  'kbd': M_kbd,
  'label': M_label,
  'liquid-metal': M_liquid_metal,
  'magnet-tabs': M_magnet_tabs,
  'magnetic-image-trail': M_magnetic_image_trail,
  'mask-cursor-effect': M_mask_cursor_effect,
  'masonry-grid': M_masonry_grid,
  'menubar': M_menubar,
  'navigation-menu': M_navigation_menu,
  'otp-input': M_otp_input,
  'pagination': M_pagination,
  'parallax-gallery': M_parallax_gallery,
  'pixelated-carousel': M_pixelated_carousel,
  'playground-button': M_playground_button,
  'playground-navbar': M_playground_navbar,
  'popover': M_popover,
  'progress': M_progress,
  'radio-group': M_radio_group,
  'raised-button': M_raised_button,
  'rectangular-text-reveal': M_rectangular_text_reveal,
  'resizable': M_resizable,
  'ripple-pulse-loader': M_ripple_pulse_loader,
  'rope-cursor': M_rope_cursor,
  'scroll-area': M_scroll_area,
  'scroll-effect': M_scroll_effect,
  'scroll-stack': M_scroll_stack,
  'select': M_select,
  'separator': M_separator,
  'sheet': M_sheet,
  'sidebar': M_sidebar,
  'sidebar-stackbits': M_sidebar_stackbits,
  'skeleton': M_skeleton,
  'skeumorphic-music-card': M_skeumorphic_music_card,
  'slider': M_slider,
  'smooth-scroll': M_smooth_scroll,
  'sonner': M_sonner,
  'spinner': M_spinner,
  'svg-path-marquee': M_svg_path_marquee,
  'svg-pixel-reveal': M_svg_pixel_reveal,
  'switch': M_switch,
  'table': M_table,
  'tabs': M_tabs,
  'text-fill-animation': M_text_fill_animation,
  'text-stream': M_text_stream,
  'textarea': M_textarea,
  'toggle': M_toggle,
  'toggle-group': M_toggle_group,
  'tooltip': M_tooltip,
  'trading-card': M_trading_card,
  'visitor-count': M_visitor_count,
};

const empty = Object.entries(modules).filter(([, m]) => Object.keys(m).length === 0);
if (empty.length) {
  throw new Error(`${empty.length} module(s) exported nothing: ${empty.map(([n]) => n).join(', ')}`);
}
console.log(`${Object.keys(modules).length} modules loaded`);
export default modules;
