#!/usr/bin/env node
// Turn upstream's usage examples into renderable demo modules for verify/.
//
//   node tools/build-demos.mjs
//
// One file per documented item, plus a registry the verify app routes on. This
// is what phase 5 records: a component cannot be filmed without knowing what
// props it needs, and the Preview block in upstream's docs is the only place
// that is written down.
//
// The demo code goes through the same brand rules as the component source. A
// demo left on upstream's palette would put their colour into every recording
// made of it — rope-cursor's example passes ropeColor="#d0b88c" and a
// bg-[#151714] container, and neither is ours.

import { writeFile, mkdir, rm, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { applyGlobal } from './lib/brand-rules.mjs';
import { stat } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'verify', 'src', 'demos');
const docs = JSON.parse(await readFile(path.join(ROOT, 'upstream', 'docs.json'), 'utf8'));

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

const names = Object.keys(docs).filter(n => docs[n].demo).sort();
const skipped = [];
const renamed = [];
const replaced = [];

/* The re-pointed usage, for the docs pages. build-site.mjs used to read
 * upstream/docs.json directly, so every item page showed upstream's original
 * example — different colours from the recording beside it, and two dead
 * references its own gates caught. */
const usage = {};

/* A demo may need its own rules — usually a prop carrying a hex that the global
 * rules cannot touch because a canvas cannot read a var(). The fix is almost
 * always to drop the prop and let the component's own re-pointed default apply. */
async function demoRules(name) {
  const p = path.join(ROOT, 'patches', `${name}.mjs`);
  try { await stat(p); } catch { return []; }
  return (await import(pathToFileURL(p).href)).demoRules ?? [];
}

for (const name of names) {
  let code = docs[name].demo;
  for (const [from, to] of await demoRules(name)) code = code.replaceAll(from, to);
  code = applyGlobal(code);

  /* Upstream writes imports against a consumer's components.json. verify/ has
   * the same aliases, so only the bare @/ form needs moving to the staged tree. */
  code = code.replace(/from ["']@\/(.*?)["']/g, 'from "@suite/$1"');

  /* Several published examples use a default import for a component that has no
   * default export — React error #130 at render, so upstream's own usage snippet
   * does not run. Checked against the staged source rather than trusted. */
  for (const m of [...code.matchAll(/import\s+([A-Z]\w*)\s+from\s+["']@suite\/(.*?)["']/g)]) {
    const [, ident, rel] = m;
    const src = await Promise.any(['tsx', 'jsx', 'ts', 'js'].map(ext =>
      readFile(path.join(ROOT, 'verify', 'src', 'suite', `${rel}.${ext}`), 'utf8'))).catch(() => null);
    if (src && !/export\s+default/.test(src)) {
      code = code.replace(m[0], `import { ${ident} } from "@suite/${rel}"`);
      renamed.push(name);
    }
  }

  /* Demo artwork. Upstream's examples want photographs that live in its own app
   * or on its CDN — both leave a recording that is an empty frame or a picture
   * of someone else's content, and upstream's guide says to replace them.
   *
   * Each distinct path maps to a plate deterministically, so a gallery of four
   * gets four different plates rather than the same one four times. */
  const plates = new Map();
  code = code.replace(/["'][^"']*\.(?:jpg|jpeg|png|webp|avif)(?:\?[^"']*)?["']/g, (m) => {
    if (m.includes('/suite/plates/')) return m;
    if (!plates.has(m)) plates.set(m, plates.size);
    const n = String((plates.get(m) % 12) + 1).padStart(2, '0');
    return `"/suite/plates/${n}.svg"`;
  });
  if (plates.size) replaced.push(`${name}(${plates.size})`);

  // An HDR environment map cannot be a plate — it is lighting data, not a
  // picture — so this one stays upstream's and is reported rather than faked.
  if (/\.hdr/.test(code)) skipped.push(name);

  /* Upstream's examples link to its own site — href="/components" is theirs,
   * and a dead reference here. The suite lives under /suite. */
  code = code.replaceAll('"/components"', '"/suite/components/"');

  await writeFile(path.join(OUT, `${name}.tsx`), `/* Generated by tools/build-demos.mjs from upstream's Preview block. */\n${code}`);
  usage[name] = code;
}

const index = `/* Generated by tools/build-demos.mjs. Do not edit. */
import { lazy } from 'react';

export const DEMOS: Record<string, React.LazyExoticComponent<React.ComponentType>> = {
${names.map(n => `  '${n}': lazy(() => import('./demos/${n}')),`).join('\n')}
};

export const DEMO_NAMES = ${JSON.stringify(names, null, 2)};
`;
await writeFile(path.join(ROOT, 'verify', 'src', 'demos.generated.ts'), index);

const uniqRenamed = [...new Set(renamed)];
await writeFile(path.join(ROOT, 'src', 'demos-usage.json'), JSON.stringify(usage, null, 2) + '\n');

console.log(`build-demos — ${names.length} demos`
  + (uniqRenamed.length ? `\n  ${uniqRenamed.length} example(s) used a default import for a named export: ${uniqRenamed.join(', ')}` : '')
  + (replaced.length ? `\n  artwork replaced with plates in ${replaced.length}: ${replaced.join(' ')}` : '')
  + (skipped.length ? `\n  ${skipped.length} still need upstream data: ${skipped.join(', ')}` : ''));
