#!/usr/bin/env node
// Turn upstream's usage examples into renderable demo modules for verify/.
//
//   node tools/build-demos.mjs
//
// One file per documented item, plus a registry the verify app routes on. This
// is what phase 5 records: a component cannot be filmed without knowing what
// props it needs, and the Preview block in upstream's docs is the only place
// that is written down.
//
// The demo code goes through the same brand rules as the component source. A
// demo left on upstream's palette would put their colour into every recording
// made of it — rope-cursor's example passes ropeColor="#d0b88c" and a
// bg-[#151714] container, and neither is ours.

import { writeFile, mkdir, rm, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { applyGlobal } from './lib/brand-rules.mjs';
import { stat } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'verify', 'src', 'demos');
const docs = JSON.parse(await readFile(path.join(ROOT, 'upstream', 'docs.json'), 'utf8'));

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

const names = Object.keys(docs).filter(n => docs[n].demo).sort();
const skipped = [];
const renamed = [];

/* A demo may need its own rules — usually a prop carrying a hex that the global
 * rules cannot touch because a canvas cannot read a var(). The fix is almost
 * always to drop the prop and let the component's own re-pointed default apply. */
async function demoRules(name) {
  const p = path.join(ROOT, 'patches', `${name}.mjs`);
  try { await stat(p); } catch { return []; }
  return (await import(pathToFileURL(p).href)).demoRules ?? [];
}

for (const name of names) {
  let code = docs[name].demo;
  for (const [from, to] of await demoRules(name)) code = code.replaceAll(from, to);
  code = applyGlobal(code);

  /* Upstream writes imports against a consumer's components.json. verify/ has
   * the same aliases, so only the bare @/ form needs moving to the staged tree. */
  code = code.replace(/from ["']@\/(.*?)["']/g, 'from "@suite/$1"');

  /* Several published examples use a default import for a component that has no
   * default export — React error #130 at render, so upstream's own usage snippet
   * does not run. Checked against the staged source rather than trusted. */
  for (const m of [...code.matchAll(/import\s+([A-Z]\w*)\s+from\s+["']@suite\/(.*?)["']/g)]) {
    const [, ident, rel] = m;
    const src = await Promise.any(['tsx', 'jsx', 'ts', 'js'].map(ext =>
      readFile(path.join(ROOT, 'verify', 'src', 'suite', `${rel}.${ext}`), 'utf8'))).catch(() => null);
    if (src && !/export\s+default/.test(src)) {
      code = code.replace(m[0], `import { ${ident} } from "@suite/${rel}"`);
      renamed.push(name);
    }
  }

  // Remote demo assets: upstream's own agent guide says to replace them. Left
  // pointing at their CDN a recording is a picture of their content.
  if (/cdn(-new)?\.obsidianui\.dev/.test(code)) skipped.push(name);

  await writeFile(path.join(OUT, `${name}.tsx`), `/* Generated by tools/build-demos.mjs from upstream's Preview block. */\n${code}`);
}

const index = `/* Generated by tools/build-demos.mjs. Do not edit. */
import { lazy } from 'react';

export const DEMOS: Record<string, React.LazyExoticComponent<React.ComponentType>> = {
${names.map(n => `  '${n}': lazy(() => import('./demos/${n}')),`).join('\n')}
};

export const DEMO_NAMES = ${JSON.stringify(names, null, 2)};
`;
await writeFile(path.join(ROOT, 'verify', 'src', 'demos.generated.ts'), index);

const uniqRenamed = [...new Set(renamed)];
console.log(`build-demos — ${names.length} demos`
  + (uniqRenamed.length ? `\n  ${uniqRenamed.length} example(s) used a default import for a named export: ${uniqRenamed.join(', ')}` : '')
  + (skipped.length ? `\n  ${skipped.length} still reference upstream's CDN: ${skipped.join(', ')}` : ''));
